"""
make_cve_pdf.py
Extract high/critical CVEs from cvelistV5-main.zip and generate a PDF
for ingestion into Milo's knowledge base.

Run from the Milo root:
    venv\Scripts\python make_cve_pdf.py

Output: Test PDFs/real/cve_high_critical.pdf
"""
import zipfile, json, sys
from pathlib import Path

ZIP    = Path(__file__).parent / "cvelistV5-main.zip"
OUT    = Path(__file__).parent / "Test PDFs" / "real" / "cve_high_critical.pdf"
TARGET = 2500
MIN_SCORE = 7.0


def cvss_score(data):
    best = 0.0
    containers = data.get("containers", {})
    sources = [containers.get("cna", {})] + containers.get("adp", [])
    for src in sources:
        for m in src.get("metrics", []):
            for key in ("cvssV4_0", "cvssV3_1", "cvssV3_0", "cvssV2_0"):
                if key in m:
                    try:
                        best = max(best, float(m[key].get("baseScore", 0)))
                    except (TypeError, ValueError):
                        pass
    return best


def en_description(data):
    try:
        for d in data["containers"]["cna"].get("descriptions", []):
            if d.get("lang", "").startswith("en"):
                return d.get("value", "").strip()
    except (KeyError, TypeError):
        pass
    return ""


def affected_summary(data):
    try:
        items = data["containers"]["cna"].get("affected", [])[:4]
        parts = []
        for a in items:
            vendor  = a.get("vendor", "")
            product = a.get("product", "")
            if vendor.lower() in ("n/a", "na", "unknown", ""):
                if product:
                    parts.append(product)
            elif product:
                parts.append(f"{vendor} {product}")
        return "; ".join(parts[:4])
    except (KeyError, TypeError):
        return ""


def severity_label(score):
    if score >= 9.0:
        return "CRITICAL"
    if score >= 7.0:
        return "HIGH"
    return "MEDIUM"


# ── scan zip ──────────────────────────────────────────────────────────────────

if not ZIP.exists() or ZIP.stat().st_size == 0:
    print(f"ERROR: {ZIP} not found or is empty.")
    print("Download from: https://github.com/CVEProject/cvelistV5/archive/refs/heads/main.zip")
    sys.exit(1)

print(f"Scanning {ZIP.name}…", flush=True)
entries = []

with zipfile.ZipFile(ZIP) as zf:
    json_files = [n for n in zf.namelist() if n.endswith(".json") and "/cves/" in n]
    total = len(json_files)
    print(f"  {total:,} CVE JSON files found", flush=True)

    for i, name in enumerate(json_files):
        if i % 20_000 == 0 and i > 0:
            print(f"  scanned {i:,}/{total:,} — collected {len(entries):,} so far", flush=True)
        try:
            with zf.open(name) as fh:
                data = json.load(fh)

            if data.get("cveMetadata", {}).get("state") != "PUBLISHED":
                continue

            score = cvss_score(data)
            if score < MIN_SCORE:
                continue

            desc = en_description(data)
            if not desc:
                continue

            entries.append({
                "id":       data["cveMetadata"]["cveId"],
                "score":    score,
                "sev":      severity_label(score),
                "desc":     desc,
                "affected": affected_summary(data),
            })
        except Exception:
            pass

print(f"\n{len(entries):,} high/critical published CVEs found.", flush=True)

# Sort highest score first (most critical/common concern at the top)
entries.sort(key=lambda x: x["score"], reverse=True)
entries = entries[:TARGET]
print(f"Taking top {len(entries):,} by CVSS score.", flush=True)

# ── generate PDF ──────────────────────────────────────────────────────────────

try:
    from fpdf import FPDF
except ImportError:
    print("ERROR: fpdf2 not installed. Run: venv\\Scripts\\pip install fpdf2")
    sys.exit(1)

SEV_COLOR = {
    "CRITICAL": (180, 20, 20),
    "HIGH":     (200, 80, 0),
    "MEDIUM":   (160, 120, 0),
}


class CVE_PDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(160, 160, 160)
        self.cell(0, 5, "CVE High/Critical Vulnerability Reference — generated by Milo", align="R")
        self.ln(5)

    def footer(self):
        self.set_y(-11)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(160, 160, 160)
        self.cell(0, 5, f"Page {self.page_no()}", align="C")


OUT.parent.mkdir(parents=True, exist_ok=True)
pdf = CVE_PDF()
pdf.set_auto_page_break(auto=True, margin=14)
pdf.add_page()

print("\nWriting PDF…", flush=True)

for i, e in enumerate(entries):
    if i % 250 == 0:
        print(f"  {i}/{len(entries)} CVEs written — page {pdf.page}", flush=True)

    r, g, b = SEV_COLOR.get(e["sev"], (100, 100, 100))

    # CVE ID + severity badge
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(r, g, b)
    pdf.multi_cell(0, 6, f"{e['id']}  [{e['sev']}  {e['score']:.1f}]")

    # Affected products
    if e["affected"]:
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(70, 70, 90)
        pdf.multi_cell(0, 5, f"Affects: {e['affected']}")

    # Description
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(20, 20, 20)
    pdf.multi_cell(0, 5, e["desc"])
    pdf.ln(4)

pdf.output(str(OUT))

size_mb = round(OUT.stat().st_size / 1_048_576, 1)
print(f"\nDone.")
print(f"  CVEs included : {len(entries):,}")
print(f"  PDF pages     : {pdf.page:,}")
print(f"  File size     : {size_mb} MB")
print(f"  Saved to      : {OUT}")
print(f"\nReady to benchmark in Milo Admin > PDF Benchmark > Reality mode.")
